FROM nginx:1.21.6

COPY ./server/ /server/
COPY ./nginx/nginx.conf /etc/nginx/
RUN apt-get update -y ; \
    apt-get install -y gcc spawn-fcgi libfcgi-dev ; \
    gcc /server/mini_serv.c -lfcgi -o ./server/server ; \
    chmod -R 755 /server/server.sh ; \
    touch /var/run/nginx.pid ; \
    chown -R nginx:nginx /var/run/nginx.pid ; \
    chown -R nginx:nginx /var/log/nginx ; \
    chown -R nginx:nginx /var/cache/nginx ; \
    rm -rf /var/lib/apt/lists

WORKDIR /server/
USER nginx

ENTRYPOINT [ "./server.sh" ]
